# Generated by Django 3.1.2 on 2020-10-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date trained')),
                ('menu', models.CharField(max_length=200)),
                ('memo', models.TextField()),
            ],
        ),
    ]
