# Generated by Django 3.1.2 on 2020-11-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0002_training'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='memo',
            new_name='training_memo',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='menu',
            new_name='training_menu',
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateTimeField(verbose_name='Training Date'),
        ),
    ]
